---
apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemis
metadata:
  name: artemis-broker
spec:
  adminUser: "admin"
  adminPassword: "admin"
  # env:
  # - name: ACTIVEMQ_PASSWORD
  #   value: <path:secret/data/activemq#password>
  deploymentPlan:
    labels:
      app: artemis-broker-app        
    annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-inject-secret-activemq.txt: "secret/activemq"
        vault.hashicorp.com/role: "myapp"        
        vault.hashicorp.com/agent-inject-template-activemq.txt: |
          {{- with secret "secret/activemq" -}}
          export ACTIVEMQ_PASSWORD={{ .Data.data.password }}
          {{- end }}
        vault.hashicorp.com/agent-inject-command-activemq: /bin/bash -c "cp /vault/secrets/activemq.txt) $HOME/activemq.sh && sh $HOME/activemq.sh" 
    podSecurity:
      serviceAccountName: activemq
    size: 2
    image: "quay.io/artemiscloud/activemq-artemis-broker-kubernetes:artemis.2.27.0"
    initImage: "quay.io/artemiscloud/activemq-artemis-broker-init:1.0.11"
    persistenceEnabled: false
    messageMigration: true
    clustered: true
    # storage:
    #   size: "5Gi"
    #   storageClassName: gp2-sc
    resources:
      limits:
        cpu: "500m"
        memory: "2048Mi"
      requests:
        cpu: "250m"
        memory: "512Mi"
  # acceptors: # (2)
  #   - name: amqp
  #     protocols: amqp
  #     port: 5672
  #     connectionsAllowed: 5
  # console: # (3)
  #   expose: true
---
apiVersion: v1
kind: Service
metadata:
  name: artemis-broker-console-0
  labels:
    ActiveMQArtemis: artemis-broker
    application: artemis-broker-app
spec:
  selector:
    ActiveMQArtemis: artemis-broker
    application: artemis-broker-app
    statefulset.kubernetes.io/pod-name: artemis-broker-ss-0
  ports:
    - name: console-0
      protocol: TCP
      port: 8161
      targetPort: 8161
  # clusterIP: None
  type: ClusterIP

---

apiVersion: v1
kind: Service
metadata:
  name: artemis-broker-console-1
  labels:
    ActiveMQArtemis: artemis-broker
    application: artemis-broker-app
spec:
  selector:
    ActiveMQArtemis: artemis-broker
    application: artemis-broker-app
    statefulset.kubernetes.io/pod-name: artemis-broker-ss-1
  ports:
    - name: console-0
      protocol: TCP
      port: 8161
      targetPort: 8161
  # clusterIP: None
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: artemis-broker-jgroups
spec:
  clusterIP: None
  ports:
    - name: 7800-7800
      port: 7800
      protocol: TCP
    - name: 7900-7900
      port: 7900
      protocol: TCP
  selector:
    ActiveMQArtemis: artemis-broker
    application: artemis-broker-app
  type: ClusterIP          
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: artemis-broker-console-0
  namespace: activemq
spec:
  ingressClassName: nginx
  rules:
    - host: one.activemq.com
      http:
        paths:
          - pathType: Prefix
            backend:
              service:
                name: artemis-broker-console-0
                port:
                  number: 8161
            path: /   

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: artemis-broker-console-1
  namespace: activemq
spec:
  ingressClassName: nginx
  rules:
    - host: two.activemq.com
      http:
        paths:
          - pathType: Prefix
            backend:
              service:
                name: artemis-broker-console-1
                port:
                  number: 8161
            path: /   

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: activemq
  labels:
    app: artemis-broker-app
    